- platform: group
  name: Living Room Ceiling
  entities:
    - light.livingroom_ceiling_1
    - light.livingroom_ceiling_2
    - light.livingroom_ceiling_3
- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp_1
    - light.living_room_lamp_2
    - light.living_room_lamp_3