- alias: Update Camera Images
  description: ''
  trigger:
  - hours: '/1'
    platform: time_pattern
  condition: []
  action:
  - data: {}
    entity_id: script.update_blink_cameras
    service: script.turn_on
  mode: single

- alias: Update USPS Mail Camera
  description: ''
  trigger:
  - entity_id: sensor.mail_usps_mail
    platform: state
  condition: []
  action:
    service: local_file.update_file_path
    data_template:
      entity_id: camera.mail_usps
      file_path: '{% if state_attr(''sensor.mail_usps_mail'',''image'') == None  %}
        /config/custom_components/mail_and_packages/mail_none.gif {% else %} /config/www/images/{{
        state_attr(''sensor.mail_usps_mail'',''image'') }} {% endif %}'
  mode: single
  
  